name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ehsanatash/temx_ui_00:latest .

      # List images for debugging
      - name: List Docker images
        run: docker images

      # Push Docker image
      - name: Push Docker image
        run: |
          docker push ehsanatash/temx_ui_00:latest

      # Confirm workflow ran
      - name: Confirm workflow ran
        run: echo "Workflow completed successfully!"